# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_token', models.CharField(max_length=4)),
                ('buy_quantity', models.FloatField()),
                ('sell_token', models.CharField(max_length=4)),
                ('sell_quantity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_token', models.CharField(max_length=4)),
                ('buy_quantity', models.FloatField()),
                ('sell_token', models.CharField(max_length=4)),
                ('sell_quantity', models.FloatField()),
                ('cancel_order', models.BooleanField()),
            ],
        ),
    ]
